package com.kcsj.pojo;

import java.util.Date;

public class appl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appl.appl_id
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    private Integer applId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appl.user_number
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    private Integer userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appl.user_name
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appl.appl_time
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    private Date applTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appl.appl_remark
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    private String applRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appl.appl_type
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    private String applType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appl.appl_status
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    private Integer applStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appl.appl_id
     *
     * @return the value of appl.appl_id
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public Integer getApplId() {
        return applId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appl.appl_id
     *
     * @param applId the value for appl.appl_id
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public void setApplId(Integer applId) {
        this.applId = applId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appl.user_number
     *
     * @return the value of appl.user_number
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appl.user_number
     *
     * @param userNumber the value for appl.user_number
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appl.user_name
     *
     * @return the value of appl.user_name
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appl.user_name
     *
     * @param userName the value for appl.user_name
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appl.appl_time
     *
     * @return the value of appl.appl_time
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public Date getApplTime() {
        return applTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appl.appl_time
     *
     * @param applTime the value for appl.appl_time
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public void setApplTime(Date applTime) {
        this.applTime = applTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appl.appl_remark
     *
     * @return the value of appl.appl_remark
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public String getApplRemark() {
        return applRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appl.appl_remark
     *
     * @param applRemark the value for appl.appl_remark
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public void setApplRemark(String applRemark) {
        this.applRemark = applRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appl.appl_type
     *
     * @return the value of appl.appl_type
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public String getApplType() {
        return applType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appl.appl_type
     *
     * @param applType the value for appl.appl_type
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public void setApplType(String applType) {
        this.applType = applType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appl.appl_status
     *
     * @return the value of appl.appl_status
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public Integer getApplStatus() {
        return applStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appl.appl_status
     *
     * @param applStatus the value for appl.appl_status
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    public void setApplStatus(Integer applStatus) {
        this.applStatus = applStatus;
    }
}