package com.kcsj.pojo;

import java.util.Date;

public class Attd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_id
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private Integer attdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.user_number
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private Integer userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_begintime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private Date attdBegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_endtime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private Date attdEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_vaction_begintime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private Date attdVactionBegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_vaction_endtime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private Date attdVactionEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_vaction_remark
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private String attdVactionRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_travel_begintime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private Date attdTravelBegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_travel_endtime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private Date attdTravelEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_travel_place
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private String attdTravelPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_travel_remark
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private String attdTravelRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_cost
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
   

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_remark
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private String attdRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_status
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    private Integer attdStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_id
     *
     * @return the value of attd.attd_id
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public Integer getAttdId() {
        return attdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_id
     *
     * @param attdId the value for attd.attd_id
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdId(Integer attdId) {
        this.attdId = attdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.user_number
     *
     * @return the value of attd.user_number
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.user_number
     *
     * @param userNumber the value for attd.user_number
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_begintime
     *
     * @return the value of attd.attd_begintime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public Date getAttdBegintime() {
        return attdBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_begintime
     *
     * @param attdBegintime the value for attd.attd_begintime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdBegintime(Date attdBegintime) {
        this.attdBegintime = attdBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_endtime
     *
     * @return the value of attd.attd_endtime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public Date getAttdEndtime() {
        return attdEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_endtime
     *
     * @param attdEndtime the value for attd.attd_endtime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdEndtime(Date attdEndtime) {
        this.attdEndtime = attdEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_vaction_begintime
     *
     * @return the value of attd.attd_vaction_begintime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public Date getAttdVactionBegintime() {
        return attdVactionBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_vaction_begintime
     *
     * @param attdVactionBegintime the value for attd.attd_vaction_begintime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdVactionBegintime(Date attdVactionBegintime) {
        this.attdVactionBegintime = attdVactionBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_vaction_endtime
     *
     * @return the value of attd.attd_vaction_endtime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public Date getAttdVactionEndtime() {
        return attdVactionEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_vaction_endtime
     *
     * @param attdVactionEndtime the value for attd.attd_vaction_endtime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdVactionEndtime(Date attdVactionEndtime) {
        this.attdVactionEndtime = attdVactionEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_vaction_remark
     *
     * @return the value of attd.attd_vaction_remark
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public String getAttdVactionRemark() {
        return attdVactionRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_vaction_remark
     *
     * @param attdVactionRemark the value for attd.attd_vaction_remark
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdVactionRemark(String attdVactionRemark) {
        this.attdVactionRemark = attdVactionRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_travel_begintime
     *
     * @return the value of attd.attd_travel_begintime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public Date getAttdTravelBegintime() {
        return attdTravelBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_travel_begintime
     *
     * @param attdTravelBegintime the value for attd.attd_travel_begintime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdTravelBegintime(Date attdTravelBegintime) {
        this.attdTravelBegintime = attdTravelBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_travel_endtime
     *
     * @return the value of attd.attd_travel_endtime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public Date getAttdTravelEndtime() {
        return attdTravelEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_travel_endtime
     *
     * @param attdTravelEndtime the value for attd.attd_travel_endtime
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdTravelEndtime(Date attdTravelEndtime) {
        this.attdTravelEndtime = attdTravelEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_travel_place
     *
     * @return the value of attd.attd_travel_place
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public String getAttdTravelPlace() {
        return attdTravelPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_travel_place
     *
     * @param attdTravelPlace the value for attd.attd_travel_place
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdTravelPlace(String attdTravelPlace) {
        this.attdTravelPlace = attdTravelPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_travel_remark
     *
     * @return the value of attd.attd_travel_remark
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public String getAttdTravelRemark() {
        return attdTravelRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_travel_remark
     *
     * @param attdTravelRemark the value for attd.attd_travel_remark
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdTravelRemark(String attdTravelRemark) {
        this.attdTravelRemark = attdTravelRemark;
    }

   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_remark
     *
     * @return the value of attd.attd_remark
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public String getAttdRemark() {
        return attdRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_remark
     *
     * @param attdRemark the value for attd.attd_remark
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdRemark(String attdRemark) {
        this.attdRemark = attdRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attd.attd_status
     *
     * @return the value of attd.attd_status
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public Integer getAttdStatus() {
        return attdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attd.attd_status
     *
     * @param attdStatus the value for attd.attd_status
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    public void setAttdStatus(Integer attdStatus) {
        this.attdStatus = attdStatus;
    }
}