package com.kcsj.pojo;


public class Attdtable {
   
    public Integer getUserNumber() {
		return userNumber;
	}

	public void setUserNumber(Integer userNumber) {
		this.userNumber = userNumber;
	}

	public int getAttdDay() {
		return attdDay;
	}

	public void setAttdDay(int attdDay) {
		this.attdDay = attdDay;
	}

	public int getAttdVactionDay() {
		return attdVactionDay;
	}

	public void setAttdVactionDay(int attdVactionDay) {
		this.attdVactionDay = attdVactionDay;
	}

	public int getAttdTravelDay() {
		return attdTravelDay;
	}

	public void setAttdTravelDay(int attdTravelDay) {
		this.attdTravelDay = attdTravelDay;
	}

	private Integer userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_begintime
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private int attdDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_endtime
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    
    private int attdVactionDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_vaction_endtime
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    
   
    private int attdTravelDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attd.attd_travel_endtime
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
   
}