package com.kcsj.pojo;

import java.util.Date;

public class Award {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_id
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Integer awardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.user_number
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Integer userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_dpt_cost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Double awardDptCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_personal_cost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Double awardPersonalCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_birth_redb
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Double awardBirthRedb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_birth_time
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Date awardBirthTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_status
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Integer awardStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_remark
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private String awardRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_id
     *
     * @return the value of award.award_id
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Integer getAwardId() {
        return awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_id
     *
     * @param awardId the value for award.award_id
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setAwardId(Integer awardId) {
        this.awardId = awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.user_number
     *
     * @return the value of award.user_number
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.user_number
     *
     * @param userNumber the value for award.user_number
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_dpt_cost
     *
     * @return the value of award.award_dpt_cost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Double getAwardDptCost() {
        return awardDptCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_dpt_cost
     *
     * @param awardDptCost the value for award.award_dpt_cost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setAwardDptCost(Double awardDptCost) {
        this.awardDptCost = awardDptCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_personal_cost
     *
     * @return the value of award.award_personal_cost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Double getAwardPersonalCost() {
        return awardPersonalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_personal_cost
     *
     * @param awardPersonalCost the value for award.award_personal_cost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setAwardPersonalCost(Double awardPersonalCost) {
        this.awardPersonalCost = awardPersonalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_birth_redb
     *
     * @return the value of award.award_birth_redb
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Double getAwardBirthRedb() {
        return awardBirthRedb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_birth_redb
     *
     * @param awardBirthRedb the value for award.award_birth_redb
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setAwardBirthRedb(Double awardBirthRedb) {
        this.awardBirthRedb = awardBirthRedb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_birth_time
     *
     * @return the value of award.award_birth_time
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Date getAwardBirthTime() {
        return awardBirthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_birth_time
     *
     * @param awardBirthTime the value for award.award_birth_time
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setAwardBirthTime(Date awardBirthTime) {
        this.awardBirthTime = awardBirthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_status
     *
     * @return the value of award.award_status
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Integer getAwardStatus() {
        return awardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_status
     *
     * @param awardStatus the value for award.award_status
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setAwardStatus(Integer awardStatus) {
        this.awardStatus = awardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_remark
     *
     * @return the value of award.award_remark
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public String getAwardRemark() {
        return awardRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_remark
     *
     * @param awardRemark the value for award.award_remark
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setAwardRemark(String awardRemark) {
        this.awardRemark = awardRemark;
    }
}