package com.kcsj.pojo;

import java.util.Date;

public class Basewage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basewage.basewage_id
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    private Integer basewageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basewage.basewage_dpt_id
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    private Integer basewageDptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basewage.basewage_dpt_name
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    private String basewageDptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basewage.basewage_dpt_jbn
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    private Integer basewageDptJbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basewage.basewage_dpt_jbname
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    private String basewageDptJbname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basewage.basewage_time
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    private Date basewageTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basewage.basewage_wage
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    private Double basewageWage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basewage.basewage_id
     *
     * @return the value of basewage.basewage_id
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public Integer getBasewageId() {
        return basewageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basewage.basewage_id
     *
     * @param basewageId the value for basewage.basewage_id
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public void setBasewageId(Integer basewageId) {
        this.basewageId = basewageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basewage.basewage_dpt_id
     *
     * @return the value of basewage.basewage_dpt_id
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public Integer getBasewageDptId() {
        return basewageDptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basewage.basewage_dpt_id
     *
     * @param basewageDptId the value for basewage.basewage_dpt_id
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public void setBasewageDptId(Integer basewageDptId) {
        this.basewageDptId = basewageDptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basewage.basewage_dpt_name
     *
     * @return the value of basewage.basewage_dpt_name
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public String getBasewageDptName() {
        return basewageDptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basewage.basewage_dpt_name
     *
     * @param basewageDptName the value for basewage.basewage_dpt_name
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public void setBasewageDptName(String basewageDptName) {
        this.basewageDptName = basewageDptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basewage.basewage_dpt_jbn
     *
     * @return the value of basewage.basewage_dpt_jbn
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public Integer getBasewageDptJbn() {
        return basewageDptJbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basewage.basewage_dpt_jbn
     *
     * @param basewageDptJbn the value for basewage.basewage_dpt_jbn
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public void setBasewageDptJbn(Integer basewageDptJbn) {
        this.basewageDptJbn = basewageDptJbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basewage.basewage_dpt_jbname
     *
     * @return the value of basewage.basewage_dpt_jbname
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public String getBasewageDptJbname() {
        return basewageDptJbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basewage.basewage_dpt_jbname
     *
     * @param basewageDptJbname the value for basewage.basewage_dpt_jbname
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public void setBasewageDptJbname(String basewageDptJbname) {
        this.basewageDptJbname = basewageDptJbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basewage.basewage_time
     *
     * @return the value of basewage.basewage_time
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public Date getBasewageTime() {
        return basewageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basewage.basewage_time
     *
     * @param basewageTime the value for basewage.basewage_time
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public void setBasewageTime(Date basewageTime) {
        this.basewageTime = basewageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basewage.basewage_wage
     *
     * @return the value of basewage.basewage_wage
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public Double getBasewageWage() {
        return basewageWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basewage.basewage_wage
     *
     * @param basewageWage the value for basewage.basewage_wage
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    public void setBasewageWage(Double basewageWage) {
        this.basewageWage = basewageWage;
    }
}