package com.kcsj.pojo;

import java.util.Date;

public class Manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mid
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerid
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    private String managerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerpassword
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    private String managerpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managername
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    private String managername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manageridCard
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    private Double manageridcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerphone
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    private Double managerphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerlogintime
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    private Date managerlogintime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mid
     *
     * @return the value of manager.mid
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mid
     *
     * @param mid the value for manager.mid
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerid
     *
     * @return the value of manager.managerid
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public String getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerid
     *
     * @param managerid the value for manager.managerid
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public void setManagerid(String managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerpassword
     *
     * @return the value of manager.managerpassword
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public String getManagerpassword() {
        return managerpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerpassword
     *
     * @param managerpassword the value for manager.managerpassword
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public void setManagerpassword(String managerpassword) {
        this.managerpassword = managerpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managername
     *
     * @return the value of manager.managername
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managername
     *
     * @param managername the value for manager.managername
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public void setManagername(String managername) {
        this.managername = managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manageridCard
     *
     * @return the value of manager.manageridCard
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public Double getManageridcard() {
        return manageridcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manageridCard
     *
     * @param manageridcard the value for manager.manageridCard
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public void setManageridcard(Double manageridcard) {
        this.manageridcard = manageridcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerphone
     *
     * @return the value of manager.managerphone
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public Double getManagerphone() {
        return managerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerphone
     *
     * @param managerphone the value for manager.managerphone
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public void setManagerphone(Double managerphone) {
        this.managerphone = managerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerlogintime
     *
     * @return the value of manager.managerlogintime
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public Date getManagerlogintime() {
        return managerlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerlogintime
     *
     * @param managerlogintime the value for manager.managerlogintime
     *
     * @mbggenerated Thu Oct 12 12:54:05 CST 2017
     */
    public void setManagerlogintime(Date managerlogintime) {
        this.managerlogintime = managerlogintime;
    }
}