package com.kcsj.pojo;

import java.util.Date;

public class Opertion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opertion.operating_id
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    private Integer operatingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opertion.manager_name
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opertion.operating_type
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    private String operatingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opertion.operating_time
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    private Date operatingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opertion.manager_id
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    private String managerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opertion.operating_id
     *
     * @return the value of opertion.operating_id
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    public Integer getOperatingId() {
        return operatingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opertion.operating_id
     *
     * @param operatingId the value for opertion.operating_id
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    public void setOperatingId(Integer operatingId) {
        this.operatingId = operatingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opertion.manager_name
     *
     * @return the value of opertion.manager_name
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opertion.manager_name
     *
     * @param managerName the value for opertion.manager_name
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opertion.operating_type
     *
     * @return the value of opertion.operating_type
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    public String getOperatingType() {
        return operatingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opertion.operating_type
     *
     * @param operatingType the value for opertion.operating_type
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    public void setOperatingType(String operatingType) {
        this.operatingType = operatingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opertion.operating_time
     *
     * @return the value of opertion.operating_time
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    public Date getOperatingTime() {
        return operatingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opertion.operating_time
     *
     * @param operatingTime the value for opertion.operating_time
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    public void setOperatingTime(Date operatingTime) {
        this.operatingTime = operatingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opertion.manager_id
     *
     * @return the value of opertion.manager_id
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opertion.manager_id
     *
     * @param managerId the value for opertion.manager_id
     *
     * @mbggenerated Mon Mar 19 21:50:36 CST 2018
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }
}