package com.kcsj.pojo;

import java.util.Date;

public class Opretion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opretion.operating_id
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    private Integer operatingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opretion.manager_name
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opretion.operating_type
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    private String operatingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opretion.operating_time
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    private Date operatingTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opretion.operating_id
     *
     * @return the value of opretion.operating_id
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    public Integer getOperatingId() {
        return operatingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opretion.operating_id
     *
     * @param operatingId the value for opretion.operating_id
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    public void setOperatingId(Integer operatingId) {
        this.operatingId = operatingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opretion.manager_name
     *
     * @return the value of opretion.manager_name
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opretion.manager_name
     *
     * @param managerName the value for opretion.manager_name
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opretion.operating_type
     *
     * @return the value of opretion.operating_type
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    public String getOperatingType() {
        return operatingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opretion.operating_type
     *
     * @param operatingType the value for opretion.operating_type
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    public void setOperatingType(String operatingType) {
        this.operatingType = operatingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opretion.operating_time
     *
     * @return the value of opretion.operating_time
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    public Date getOperatingTime() {
        return operatingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opretion.operating_time
     *
     * @param operatingTime the value for opretion.operating_time
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    public void setOperatingTime(Date operatingTime) {
        this.operatingTime = operatingTime;
    }
}