package com.kcsj.pojo;

public class Recard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recard.recard_id
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    private Integer recardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recard.recard_usernumber
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    private Integer recardUsernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recard.recard_managerid
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    private String recardManagerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recard.recard_reason
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    private String recardReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recard.recard_id
     *
     * @return the value of recard.recard_id
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    public Integer getRecardId() {
        return recardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recard.recard_id
     *
     * @param recardId the value for recard.recard_id
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    public void setRecardId(Integer recardId) {
        this.recardId = recardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recard.recard_usernumber
     *
     * @return the value of recard.recard_usernumber
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    public Integer getRecardUsernumber() {
        return recardUsernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recard.recard_usernumber
     *
     * @param recardUsernumber the value for recard.recard_usernumber
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    public void setRecardUsernumber(Integer recardUsernumber) {
        this.recardUsernumber = recardUsernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recard.recard_managerid
     *
     * @return the value of recard.recard_managerid
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    public String getRecardManagerid() {
        return recardManagerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recard.recard_managerid
     *
     * @param recardManagerid the value for recard.recard_managerid
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    public void setRecardManagerid(String recardManagerid) {
        this.recardManagerid = recardManagerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recard.recard_reason
     *
     * @return the value of recard.recard_reason
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    public String getRecardReason() {
        return recardReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recard.recard_reason
     *
     * @param recardReason the value for recard.recard_reason
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    public void setRecardReason(String recardReason) {
        this.recardReason = recardReason;
    }
}