package com.kcsj.pojo;

import java.util.Date;

public class Travelcostall {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcostall.travelcostall_id
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private Integer travelcostallId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcostall.user_number
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private Integer userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcostall.travelcostall_time
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private Date travelcostallTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcostall.travelcostall_cost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private Double travelcostallCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcostall.travelcostall_status
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private Integer travelcostallStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcostall.travelcostall_remark
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private String travelcostallRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcostall.travelcostall_id
     *
     * @return the value of travelcostall.travelcostall_id
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public Integer getTravelcostallId() {
        return travelcostallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcostall.travelcostall_id
     *
     * @param travelcostallId the value for travelcostall.travelcostall_id
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostallId(Integer travelcostallId) {
        this.travelcostallId = travelcostallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcostall.user_number
     *
     * @return the value of travelcostall.user_number
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcostall.user_number
     *
     * @param userNumber the value for travelcostall.user_number
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcostall.travelcostall_time
     *
     * @return the value of travelcostall.travelcostall_time
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public Date getTravelcostallTime() {
        return travelcostallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcostall.travelcostall_time
     *
     * @param travelcostallTime the value for travelcostall.travelcostall_time
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostallTime(Date travelcostallTime) {
        this.travelcostallTime = travelcostallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcostall.travelcostall_cost
     *
     * @return the value of travelcostall.travelcostall_cost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public Double getTravelcostallCost() {
        return travelcostallCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcostall.travelcostall_cost
     *
     * @param travelcostallCost the value for travelcostall.travelcostall_cost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostallCost(Double travelcostallCost) {
        this.travelcostallCost = travelcostallCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcostall.travelcostall_status
     *
     * @return the value of travelcostall.travelcostall_status
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public Integer getTravelcostallStatus() {
        return travelcostallStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcostall.travelcostall_status
     *
     * @param travelcostallStatus the value for travelcostall.travelcostall_status
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostallStatus(Integer travelcostallStatus) {
        this.travelcostallStatus = travelcostallStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcostall.travelcostall_remark
     *
     * @return the value of travelcostall.travelcostall_remark
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public String getTravelcostallRemark() {
        return travelcostallRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcostall.travelcostall_remark
     *
     * @param travelcostallRemark the value for travelcostall.travelcostall_remark
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostallRemark(String travelcostallRemark) {
        this.travelcostallRemark = travelcostallRemark;
    }
}