package com.kcsj.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_number
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private Integer userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_dpt
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private Integer userDpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_dpt_jbn
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private String userDptJbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_username
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private String userUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_sex
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private Integer userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_birth
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private Date userBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_phone
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private Double userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_idCard
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private String userIdcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_bankCard
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private String userBankcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_address
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_dangerphone
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private Double userDangerphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_worktime
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private Date userWorktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_jobtype
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private Integer userJobtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_worktype
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private Integer userWorktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_account
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_nikename
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private String userNikename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_edu
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    private String userEdu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_number
     *
     * @return the value of user.user_number
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_number
     *
     * @param userNumber the value for user.user_number
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_dpt
     *
     * @return the value of user.user_dpt
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public Integer getUserDpt() {
        return userDpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_dpt
     *
     * @param userDpt the value for user.user_dpt
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserDpt(Integer userDpt) {
        this.userDpt = userDpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_dpt_jbn
     *
     * @return the value of user.user_dpt_jbn
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public String getUserDptJbn() {
        return userDptJbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_dpt_jbn
     *
     * @param userDptJbn the value for user.user_dpt_jbn
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserDptJbn(String userDptJbn) {
        this.userDptJbn = userDptJbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_username
     *
     * @return the value of user.user_username
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public String getUserUsername() {
        return userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_username
     *
     * @param userUsername the value for user.user_username
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_sex
     *
     * @return the value of user.user_sex
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_sex
     *
     * @param userSex the value for user.user_sex
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_birth
     *
     * @return the value of user.user_birth
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public Date getUserBirth() {
        return userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_birth
     *
     * @param userBirth the value for user.user_birth
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserBirth(Date userBirth) {
        this.userBirth = userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_phone
     *
     * @return the value of user.user_phone
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public Double getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_phone
     *
     * @param userPhone the value for user.user_phone
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserPhone(Double userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_idCard
     *
     * @return the value of user.user_idCard
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public String getUserIdcard() {
        return userIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_idCard
     *
     * @param userIdcard the value for user.user_idCard
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserIdcard(String userIdcard) {
        this.userIdcard = userIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_bankCard
     *
     * @return the value of user.user_bankCard
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public String getUserBankcard() {
        return userBankcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_bankCard
     *
     * @param userBankcard the value for user.user_bankCard
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserBankcard(String userBankcard) {
        this.userBankcard = userBankcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_address
     *
     * @return the value of user.user_address
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_address
     *
     * @param userAddress the value for user.user_address
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_dangerphone
     *
     * @return the value of user.user_dangerphone
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public Double getUserDangerphone() {
        return userDangerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_dangerphone
     *
     * @param userDangerphone the value for user.user_dangerphone
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserDangerphone(Double userDangerphone) {
        this.userDangerphone = userDangerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_worktime
     *
     * @return the value of user.user_worktime
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public Date getUserWorktime() {
        return userWorktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_worktime
     *
     * @param userWorktime the value for user.user_worktime
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserWorktime(Date userWorktime) {
        this.userWorktime = userWorktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_jobtype
     *
     * @return the value of user.user_jobtype
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public Integer getUserJobtype() {
        return userJobtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_jobtype
     *
     * @param userJobtype the value for user.user_jobtype
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserJobtype(Integer userJobtype) {
        this.userJobtype = userJobtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_worktype
     *
     * @return the value of user.user_worktype
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public Integer getUserWorktype() {
        return userWorktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_worktype
     *
     * @param userWorktype the value for user.user_worktype
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserWorktype(Integer userWorktype) {
        this.userWorktype = userWorktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_account
     *
     * @return the value of user.user_account
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_account
     *
     * @param userAccount the value for user.user_account
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_nikename
     *
     * @return the value of user.user_nikename
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public String getUserNikename() {
        return userNikename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_nikename
     *
     * @param userNikename the value for user.user_nikename
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserNikename(String userNikename) {
        this.userNikename = userNikename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_edu
     *
     * @return the value of user.user_edu
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public String getUserEdu() {
        return userEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_edu
     *
     * @param userEdu the value for user.user_edu
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    public void setUserEdu(String userEdu) {
        this.userEdu = userEdu;
    }
}