package com.kcsj.pojo;

import java.util.Date;

public class Wage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_id
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Integer wageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.user_number
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Integer userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_attd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Integer wageAttd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_notattd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Integer wageNotattd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_vacation
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Integer wageVacation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_travel
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Integer wageTravel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_travelcostall
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Double wageTravelcostall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_birth
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Double wageBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_personal
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Double wagePersonal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_dpt
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Double wageDpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_basswage
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Double wageBasswage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_attdcost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Double wageAttdcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_allwage
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Double wageAllwage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_tobank
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Integer wageTobank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_allwagetime
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private Date wageAllwagetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.wage_remark
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    private String wageRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_id
     *
     * @return the value of wage.wage_id
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Integer getWageId() {
        return wageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_id
     *
     * @param wageId the value for wage.wage_id
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageId(Integer wageId) {
        this.wageId = wageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.user_number
     *
     * @return the value of wage.user_number
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.user_number
     *
     * @param userNumber the value for wage.user_number
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_attd
     *
     * @return the value of wage.wage_attd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Integer getWageAttd() {
        return wageAttd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_attd
     *
     * @param wageAttd the value for wage.wage_attd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageAttd(Integer wageAttd) {
        this.wageAttd = wageAttd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_notattd
     *
     * @return the value of wage.wage_notattd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Integer getWageNotattd() {
        return wageNotattd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_notattd
     *
     * @param wageNotattd the value for wage.wage_notattd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageNotattd(Integer wageNotattd) {
        this.wageNotattd = wageNotattd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_vacation
     *
     * @return the value of wage.wage_vacation
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Integer getWageVacation() {
        return wageVacation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_vacation
     *
     * @param wageVacation the value for wage.wage_vacation
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageVacation(Integer wageVacation) {
        this.wageVacation = wageVacation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_travel
     *
     * @return the value of wage.wage_travel
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Integer getWageTravel() {
        return wageTravel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_travel
     *
     * @param wageTravel the value for wage.wage_travel
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageTravel(Integer wageTravel) {
        this.wageTravel = wageTravel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_travelcostall
     *
     * @return the value of wage.wage_travelcostall
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Double getWageTravelcostall() {
        return wageTravelcostall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_travelcostall
     *
     * @param wageTravelcostall the value for wage.wage_travelcostall
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageTravelcostall(Double wageTravelcostall) {
        this.wageTravelcostall = wageTravelcostall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_birth
     *
     * @return the value of wage.wage_birth
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Double getWageBirth() {
        return wageBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_birth
     *
     * @param wageBirth the value for wage.wage_birth
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageBirth(Double wageBirth) {
        this.wageBirth = wageBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_personal
     *
     * @return the value of wage.wage_personal
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Double getWagePersonal() {
        return wagePersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_personal
     *
     * @param wagePersonal the value for wage.wage_personal
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWagePersonal(Double wagePersonal) {
        this.wagePersonal = wagePersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_dpt
     *
     * @return the value of wage.wage_dpt
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Double getWageDpt() {
        return wageDpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_dpt
     *
     * @param wageDpt the value for wage.wage_dpt
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageDpt(Double wageDpt) {
        this.wageDpt = wageDpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_basswage
     *
     * @return the value of wage.wage_basswage
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Double getWageBasswage() {
        return wageBasswage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_basswage
     *
     * @param wageBasswage the value for wage.wage_basswage
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageBasswage(Double wageBasswage) {
        this.wageBasswage = wageBasswage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_attdcost
     *
     * @return the value of wage.wage_attdcost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Double getWageAttdcost() {
        return wageAttdcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_attdcost
     *
     * @param wageAttdcost the value for wage.wage_attdcost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageAttdcost(Double wageAttdcost) {
        this.wageAttdcost = wageAttdcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_allwage
     *
     * @return the value of wage.wage_allwage
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Double getWageAllwage() {
        return wageAllwage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_allwage
     *
     * @param wageAllwage the value for wage.wage_allwage
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageAllwage(Double wageAllwage) {
        this.wageAllwage = wageAllwage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_tobank
     *
     * @return the value of wage.wage_tobank
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Integer getWageTobank() {
        return wageTobank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_tobank
     *
     * @param wageTobank the value for wage.wage_tobank
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageTobank(Integer wageTobank) {
        this.wageTobank = wageTobank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_allwagetime
     *
     * @return the value of wage.wage_allwagetime
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public Date getWageAllwagetime() {
        return wageAllwagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_allwagetime
     *
     * @param wageAllwagetime the value for wage.wage_allwagetime
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageAllwagetime(Date wageAllwagetime) {
        this.wageAllwagetime = wageAllwagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.wage_remark
     *
     * @return the value of wage.wage_remark
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public String getWageRemark() {
        return wageRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.wage_remark
     *
     * @param wageRemark the value for wage.wage_remark
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    public void setWageRemark(String wageRemark) {
        this.wageRemark = wageRemark;
    }
}