package com.kcsj.dao;

import java.util.List;

import com.kcsj.pojo.Appl;

public interface ApplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Mon Apr 09 21:40:03 CST 2018
     */
    int deleteByPrimaryKey(Integer applId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Mon Apr 09 21:40:03 CST 2018
     */
    int insert(Appl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Mon Apr 09 21:40:03 CST 2018
     */
    int insertSelective(Appl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Mon Apr 09 21:40:03 CST 2018
     */
    Appl selectByPrimaryKey(Integer applId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Mon Apr 09 21:40:03 CST 2018
     */
    int updateByPrimaryKeySelective(Appl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Mon Apr 09 21:40:03 CST 2018
     */
    int updateByPrimaryKey(Appl record);
    
  //通知查找（appl_type="请假" or 休假  or出差 ）
    List<Appl> findAllApplByApp_type1(String managerid);
    
    //消息查找（appl_type="请示"）
    List<Appl> findAllApplByApp_type2(String managerid);
    
    /**
     *同意appl
     */
    public int agreeappl(int usernumber); 
    
    /**
     *拒绝appl
     */
    public int refuseappl(int usernumber); 
    
    //更改员工工作状态：查找worktype
    Appl findAllApplByusernumber(int usernumber);
    
    /*
     * 人员安排：查找员工请假、休假、出差成功的人
     */
    List<Appl> findApplByApp_type1();
    
    /*
     * 人员安排；修改员工appl_jijue
     */
    int UpApplByUid(int uid);
}