package com.kcsj.dao;

import java.util.List;


import com.kcsj.pojo.appl;

public interface applMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    int deleteByPrimaryKey(Integer applId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    int insert(appl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    int insertSelective(appl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    appl selectByPrimaryKey(Integer applId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    int updateByPrimaryKeySelective(appl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appl
     *
     * @mbggenerated Tue Oct 10 15:44:57 CST 2017
     */
    int updateByPrimaryKey(appl record);
    
    /**
     *查找appl今日模糊
     */
    public List<appl> findappl(String text);
    
    /**
     *查找appl今日所有信息
     */
    public List<appl> findappl2(); 
    
    /**
     *查找appl历史所有信息
     */
    public List<appl> findappl3(); 
    
    /**
     *查找appl历史模糊查询
     */
    public List<appl> findappl4(String text); 
    
    /**
     *同意appl
     */
    public int agreeappl(String usernumber); 
    
    /**
     *拒绝appl
     */
    public int refuseappl(String usernumber); 
    
    /**
     *提醒appl
     */
    public int remindappl(String usernumber); 
}