package com.kcsj.dao;

import java.util.List;

import com.kcsj.entitl.preAttdData;
import com.kcsj.pojo.Attd;

public interface AttdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    int deleteByPrimaryKey(Integer attdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    int insert(Attd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    int insertSelective(Attd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    Attd selectByPrimaryKey(Integer attdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    int updateByPrimaryKeySelective(Attd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Thu Apr 05 10:51:25 CST 2018
     */
    int updateByPrimaryKey(Attd record);
    
    /**
     * 考勤数据：查找员工的考勤信息(考勤管理，当天)
     */
    List<preAttdData> findattdayAll ();
    
    /**
     * 考勤数据：查找单个员工的所有考勤信息(考勤管理，历史)
     */
    List<preAttdData> findUserAttdayAll (String usernumber);
}