package com.kcsj.dao;

import java.util.List;

import com.kcsj.entity.AttdData;
import com.kcsj.pojo.Attd;
import com.kcsj.pojo.Attdtable;

public interface AttdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int deleteByPrimaryKey(Integer attdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int insert(Attd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int insertSelective(Attd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    Attd selectByPrimaryKey(Integer attdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int updateByPrimaryKeySelective(Attd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attd
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int updateByPrimaryKey(Attd record);
    
    /**
     * 查找员工的考勤信息
     */
    int findattday (String usernumber);
    
    int findvacationday (String usernumber);
    
    int findtravelday (String usernumber);
    
    
    /**
     * 查找员工的考勤信息(考勤管理，当天)
     */
    List<AttdData> findattdayAll ();
    
    /**
     * 查找单个员工的所有考勤信息(考勤管理，历史)
     */
    List<AttdData> findUserAttdayAll (String usernumber);
    
    /**
     * 查找单个员工的考勤信息(考勤管理，当天，查询功能)
     */
    List<AttdData> findUserAttday (String usernumber);
    
    
    /**
     * 查找员工的休假信息(考勤管理，当天)
     */
    List<AttdData> findvacationdayAll ();
    
    /**
     * 查找单个员工的所有休假信息(考勤管理，历史)
     */
    List<AttdData> findUserVacationdayAll (String usernumber);
    
    /**
     * 查找单个员工的休假信息(考勤管理，当天，查询功能)
     */
    List<AttdData> findUserVacationday (String usernumber);
    
    /**
     * 查找员工的出差信息(考勤管理，当天)
     */
    List<AttdData> findTraveldayAll ();
    
    /**
     * 查找单个员工的所有出差信息(考勤管理，历史)
     */
    List<AttdData> findUserTravelAll (String usernumber);
    
    /**
     * 查找单个员工的出差信息(考勤管理，当天，查询功能)
     */
    List<AttdData> findUserTravelday (String usernumber);
    
}