package com.kcsj.dao;

import java.util.List;

import com.kcsj.entitl.Award1;
import com.kcsj.pojo.Award;

public interface AwardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Apr 30 13:30:07 CST 2018
     */
    int deleteByPrimaryKey(Integer awardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Apr 30 13:30:07 CST 2018
     */
    int insert(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Apr 30 13:30:07 CST 2018
     */
    int insertSelective(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Apr 30 13:30:07 CST 2018
     */
    Award selectByPrimaryKey(Integer awardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Apr 30 13:30:07 CST 2018
     */
    int updateByPrimaryKeySelective(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Apr 30 13:30:07 CST 2018
     */
    int updateByPrimaryKey(Award record);
    List<Award1>  findall();
    List<Award1>  findall2(int uid);
    Award  findallAward(int uid);
}