package com.kcsj.dao;

import com.kcsj.pojo.Award;

public interface AwardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int deleteByPrimaryKey(Integer awardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int insert(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int insertSelective(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    Award selectByPrimaryKey(Integer awardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int updateByPrimaryKeySelective(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int updateByPrimaryKey(Award record);
}