package com.kcsj.dao;

import com.kcsj.pojo.Basewage;

public interface BasewageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Apr 09 22:02:01 CST 2018
     */
    int deleteByPrimaryKey(Integer basewageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Apr 09 22:02:01 CST 2018
     */
    int insert(Basewage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Apr 09 22:02:01 CST 2018
     */
    int insertSelective(Basewage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Apr 09 22:02:01 CST 2018
     */
    Basewage selectByPrimaryKey(Integer basewageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Apr 09 22:02:01 CST 2018
     */
    int updateByPrimaryKeySelective(Basewage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Apr 09 22:02:01 CST 2018
     */
    int updateByPrimaryKey(Basewage record);
}