package com.kcsj.dao;

import com.kcsj.pojo.Basewage;

public interface BasewageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    int deleteByPrimaryKey(Integer basewageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    int insert(Basewage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    int insertSelective(Basewage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    Basewage selectByPrimaryKey(Integer basewageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    int updateByPrimaryKeySelective(Basewage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basewage
     *
     * @mbggenerated Mon Oct 30 11:22:41 CST 2017
     */
    int updateByPrimaryKey(Basewage record);
    
    //查询部门名称(根据员工部门编号)
    Basewage selectByUserdpt(Integer userdpt);
}