package com.kcsj.dao;


import com.kcsj.pojo.Manager;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Tue Mar 06 22:20:19 CST 2018
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Tue Mar 06 22:20:19 CST 2018
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Tue Mar 06 22:20:19 CST 2018
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Tue Mar 06 22:20:19 CST 2018
     */
    Manager selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Tue Mar 06 22:20:19 CST 2018
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Tue Mar 06 22:20:19 CST 2018
     */
    int updateByPrimaryKey(Manager record);
    
    /*
     * 根据username和password查找manager所有信息
     */
    Manager selectManagerByUsernamePassword(Manager m);
    
    /**
     *管理员密码修改
     */
    public int UpdateManagerpassword(Manager m); 
    
    /**
     *管理员最近时间登入时间更改
     */
    public int UpdateManagerlogintime(Manager m); 
}