package com.kcsj.dao;

import com.kcsj.pojo.Opretion;

public interface OpretionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opretion
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int deleteByPrimaryKey(Integer operatingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opretion
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int insert(Opretion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opretion
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int insertSelective(Opretion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opretion
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    Opretion selectByPrimaryKey(Integer operatingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opretion
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int updateByPrimaryKeySelective(Opretion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opretion
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int updateByPrimaryKey(Opretion record);
}