package com.kcsj.dao;

import com.kcsj.pojo.Recard;

public interface RecardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recard
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    int deleteByPrimaryKey(Integer recardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recard
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    int insert(Recard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recard
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    int insertSelective(Recard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recard
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    Recard selectByPrimaryKey(Integer recardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recard
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    int updateByPrimaryKeySelective(Recard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recard
     *
     * @mbggenerated Wed Apr 04 22:48:20 CST 2018
     */
    int updateByPrimaryKey(Recard record);
}