package com.kcsj.dao;

import com.kcsj.pojo.Travelcost;

public interface TravelcostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int deleteByPrimaryKey(Integer travelcostId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int insert(Travelcost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int insertSelective(Travelcost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    Travelcost selectByPrimaryKey(Integer travelcostId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int updateByPrimaryKeySelective(Travelcost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int updateByPrimaryKey(Travelcost record);
}