package com.kcsj.dao;

import com.kcsj.pojo.Travelcostall;

public interface TravelcostallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcostall
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int deleteByPrimaryKey(Integer travelcostallId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcostall
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int insert(Travelcostall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcostall
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int insertSelective(Travelcostall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcostall
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    Travelcostall selectByPrimaryKey(Integer travelcostallId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcostall
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int updateByPrimaryKeySelective(Travelcostall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcostall
     *
     * @mbggenerated Mon Oct 09 18:19:02 CST 2017
     */
    int updateByPrimaryKey(Travelcostall record);
}