package com.kcsj.dao;

import java.util.List;

import com.kcsj.entitl.Travelcost2;
import com.kcsj.entitl.TravelcostNew;
import com.kcsj.pojo.Travelcost;
public interface TravelcostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int deleteByPrimaryKey(Integer travelcostId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int insert(Travelcost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int insertSelective(Travelcost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    Travelcost selectByPrimaryKey(Integer travelcostId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int updateByPrimaryKeySelective(Travelcost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelcost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int updateByPrimaryKey(Travelcost record);
    
    /*
     * 差旅报销：刷新申请以及所有数据
     */
    public List<Travelcost2> FindCountTravelCost();
    
    /*
     * 差旅报销：同意修改状态
     */
    public int UpTravelCost1(int uid);
    
    /*
     * 差旅报销：拒绝修改状态
     */
    public int UpTravelCost2(int uid);
}