package com.kcsj.dao;

import java.util.List;

import com.kcsj.pojo.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int updateByPrimaryKey(User record);
    
    //查找所有员工
    public List<User> FindAllUser( );
    
    //模糊查找员工
    public List<User> FindAllUserByUidUname(String  text);
    
    /*
     * 自动生成员工编号
     */
    public int autousernumber(int dpt );
    
    /*
     *员工新增
     */
    public int insertuser(User u);
}