package com.kcsj.dao;

import java.util.List;

import com.kcsj.pojo.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Oct 18 14:59:09 CST 2017
     */
    int updateByPrimaryKey(User record);
    
    /**
     *自动生成员工编号
     */
    public int autousernumber(int m); 
    
    /**
     *员工新增
     */
    public int insertuser(User u);
    
    /**
     *查询所有员工
     */
    public List<User> selectAlluser(); 
    
    
    /**
     *查询单个员工
     */
    public List<User> selectuser(String username); 
    
    /**
     *查询单个员工
     */
    public User selectuserbyusernumber(String usernumber); 
    
    /**
     *员工离职办理
     */
    public int deletetuser(String usernumber); 
    
    /**
     *员工在职状态修改
     */
    public int upworkjob(User user); 
  
    
    //查询员工信息(人员安排)
    public List<User> selectuserForAnPai(); 
}