package com.kcsj.dao;

import java.util.List;

import com.kcsj.entitl.TravelcostNew;
import com.kcsj.entitl.UpAppl;
import com.kcsj.pojo.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    int updateByPrimaryKey(User record);
    
    //查找所有员工
    public List<User> FindAllUser( );
    
    
    /*
     * 自动生成员工编号
     */
    public int autousernumber(int dpt );
    
    /*
     *员工新增
     */
    public int insertuser(User u);
    
    /*
     * 员工新增：判断该员工是否入职
     */
    public User CheckIdCard(String idcard);
    
    /*
     * 职员转正:查询单个员工
     */
    public User updatauserByUser_number(int usernumber);
    
    /*
     * 职员转正:修改员工职位状态
     */
    public int updataUserByUser_number(User u);
    
    /*
     * 职员档案:通过员工工号，查找相关信息
     */
    public User lookuserByUid(int uid);
    
    /*
     * 职员离职:通过员工工号或者员工身份证，查找相关信息
     */
    public User LiZhiUserByUid(String uid);
    
    /*
     * 职员离职:通过usernumber，修改员工职位状态
     */
    public int SurelizhiUser(String uid);
    
    /*
     *  :通过usernumber和worktype，修改员工职位状态
     */
    public int SurelizhiUserAndUpUser(UpAppl ap);
    
    /*
     * 人员安排：查找该部门的其它人
     */
    public List<User> findUserByUser_dpt(User dpt);
    
    /*
     * 人员安排：查找在休假的所有员工
     */
    public List<User> findUserByUser_dpt2();
    
    /*
     * 人员安排：修改员工的工作状态
     */
    public int UpUserWorktypeByUsernumber(int uid);
    
  
}