package com.kcsj.dao;

import java.util.List;

import com.kcsj.entitl.Wage1;
import com.kcsj.pojo.Wage;

public interface WageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int deleteByPrimaryKey(Integer wageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int insert(Wage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int insertSelective(Wage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    Wage selectByPrimaryKey(Integer wageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int updateByPrimaryKeySelective(Wage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int updateByPrimaryKey(Wage record);
    
    /*
     * 员工薪酬汇总查询
     */
    List<Wage1> findall();
    
    /*
     * 员工薪酬汇总(发放员工工资)
     */
    int UpdateWage(int userNumber);
    
    /*
     * 员工薪酬汇总(查看员工最近半年工资状况)
     */
    List<Wage1> SelectWage(int uid);
}