package com.kcsj.dao;

import com.kcsj.pojo.Wage;

public interface WageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int deleteByPrimaryKey(Integer wageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int insert(Wage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int insertSelective(Wage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    Wage selectByPrimaryKey(Integer wageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int updateByPrimaryKeySelective(Wage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    int updateByPrimaryKey(Wage record);
}