package com.kcsj.entitl;

import java.util.Date;

public class TravelcostNew {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcost.travelcost_id
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private Integer travelcostId;

    private String userName;
    
    private String userDpt;
    
    private String userDptJbn;
    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserDpt() {
		return userDpt;
	}

	public void setUserDpt(String userDpt) {
		this.userDpt = userDpt;
	}

	public String getUserDptJbn() {
		return userDptJbn;
	}

	public void setUserDptJbn(String userDptJbn) {
		this.userDptJbn = userDptJbn;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcost.user_number
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private Integer userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcost.travelcost_type
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private String travelcostType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcost.travelcost_time
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private String travelcostTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcost.travelcost_cost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private Double travelcostCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcost.travelcost_status
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private Integer travelcostStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelcost.travelcost_remark
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    private String travelcostRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcost.travelcost_id
     *
     * @return the value of travelcost.travelcost_id
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public Integer getTravelcostId() {
        return travelcostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcost.travelcost_id
     *
     * @param travelcostId the value for travelcost.travelcost_id
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostId(Integer travelcostId) {
        this.travelcostId = travelcostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcost.user_number
     *
     * @return the value of travelcost.user_number
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcost.user_number
     *
     * @param userNumber the value for travelcost.user_number
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcost.travelcost_type
     *
     * @return the value of travelcost.travelcost_type
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public String getTravelcostType() {
        return travelcostType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcost.travelcost_type
     *
     * @param travelcostType the value for travelcost.travelcost_type
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostType(String travelcostType) {
        this.travelcostType = travelcostType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcost.travelcost_time
     *
     * @return the value of travelcost.travelcost_time
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public String getTravelcostTime() {
        return travelcostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcost.travelcost_time
     *
     * @param travelcostTime the value for travelcost.travelcost_time
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostTime(String travelcostTime) {
        this.travelcostTime = travelcostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcost.travelcost_cost
     *
     * @return the value of travelcost.travelcost_cost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public Double getTravelcostCost() {
        return travelcostCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcost.travelcost_cost
     *
     * @param travelcostCost the value for travelcost.travelcost_cost
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostCost(Double travelcostCost) {
        this.travelcostCost = travelcostCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcost.travelcost_status
     *
     * @return the value of travelcost.travelcost_status
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public Integer getTravelcostStatus() {
        return travelcostStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcost.travelcost_status
     *
     * @param travelcostStatus the value for travelcost.travelcost_status
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostStatus(Integer travelcostStatus) {
        this.travelcostStatus = travelcostStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelcost.travelcost_remark
     *
     * @return the value of travelcost.travelcost_remark
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public String getTravelcostRemark() {
        return travelcostRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelcost.travelcost_remark
     *
     * @param travelcostRemark the value for travelcost.travelcost_remark
     *
     * @mbggenerated Fri Apr 06 22:05:22 CST 2018
     */
    public void setTravelcostRemark(String travelcostRemark) {
        this.travelcostRemark = travelcostRemark;
    }
}