package com.kcsj.entitl;

import java.util.Date;

public class updateUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_number
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    private Integer userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_dpt
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    private String userDpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_dpt_jbn
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    private String userDptJbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_username
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    private String userUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_sex
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    

    private Date userWorktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_jobtype
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
    private String userJobtype;
    
    private String userWorktype;

	public String getUserWorktype() {
		return userWorktype;
	}

	public void setUserWorktype(String userWorktype) {
		this.userWorktype = userWorktype;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getUserNumber() {
		return userNumber;
	}

	public void setUserNumber(Integer userNumber) {
		this.userNumber = userNumber;
	}

	public String getUserDpt() {
		return userDpt;
	}

	public void setUserDpt(String userDpt) {
		this.userDpt = userDpt;
	}

	public String getUserDptJbn() {
		return userDptJbn;
	}

	public void setUserDptJbn(String userDptJbn) {
		this.userDptJbn = userDptJbn;
	}

	public String getUserUsername() {
		return userUsername;
	}

	public void setUserUsername(String userUsername) {
		this.userUsername = userUsername;
	}

	public Date getUserWorktime() {
		return userWorktime;
	}

	public void setUserWorktime(Date userWorktime) {
		this.userWorktime = userWorktime;
	}

	public String getUserJobtype() {
		return userJobtype;
	}

	public void setUserJobtype(String userJobtype) {
		this.userJobtype = userJobtype;
	}

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_worktype
     *
     * @mbggenerated Tue Mar 06 22:26:40 CST 2018
     */
  
  
  
}